input AddTaskRequest {
  user: String!
  email: String!
  title: String!
  description: String!
  "Due date in ISO format"
  dueDate: DateTime!
  "List of categories"
  category: [String]
  status: Status!
}

extend type Mutation {
  addTask(request: AddTaskRequest): Task
}
